# Generated by Django 4.2.1 on 2023-06-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_produktas_kategorija'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produktas',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='produktas',
            name='prodapp',
        ),
        migrations.AlterField(
            model_name='produktas',
            name='kategorija',
            field=models.CharField(choices=[('M', 'Medziaga'), ('O', 'Oda'), ('U', 'Universalus'), ('R', 'Rinkiniai'), ('SE', 'Sepeciai')], max_length=2),
        ),
    ]
