# Generated by Django 4.2.1 on 2023-06-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
    ]
