# Generated by Django 4.2.1 on 2023-06-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_payment_user_rename_user_cart_vartotojas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='vartotojas',
            new_name='user',
        ),
    ]
